import Head from 'next/head';
import Nav from '../components/Nav'
import MobileNav from '../components/MobileNav';
import Section from '../components/Section';
import MainStandard from '../components/MainStandard';
import Services from '../components/Services';
import Experience from '../components/Experience';
import Reviews from '../components/Reviews';
import Contact from '../components/Contact';
import Footer from '../components/Footer';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <MobileNav />
      <main className="pt-14 container mx-auto">
        <MainStandard />
        <Services />
        <Experience />
        <Reviews />
        <Contact />
      </main>
      <Footer />
    </div>
  )
}
