import Head from 'next/head';
import Layout from '../components/Layout';
import MainStandard from '../components/MainStandard';
import Services from '../components/pages/main/Services';
import Experience from '../components/pages/main/Experience';
import Reviews from '../components/pages/main/Reviews';
import Contact from '../components/pages/main/Contact';

// const BLOG_URL = 'https://ubat.herokuapp.com/'
// const CONTENT_API_KEY = '806e85bd11db6cdb4369bee1a8'




export default function Home() {
  return (
    <Layout className="overflow-hidden">
      <Head>
        <title>AT Upgrades Basic Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      <MainStandard />
      <Services />
      <Experience />
      <Reviews />
      <Contact />
    </Layout>
  )
}
